spring:
  datasource:
    driver-class-name=com:
      mysql:
        cj:
          jdbc:
            Driver:
    url: jdbc:mysql://3.37.151.68:3306/sofaware?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
    database: mysql

  security:
    user:
      name: root
      password: 1234

  profiles:
    include: oauth,security

logging:
  file:
    name: /log/test.log
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
